[package]
name = "fabushi-chatgpt-desktop-process"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fabushi-chatgpt-application = { path = "../../application" }
tokio.workspace = true
